'use strict'
define(function (require) {
	require('components/staff_change/directives/tests')
	require('components/staff_change/directives/forms/confirm')
	require('components/staff_change/directives/forms/creation_checks')
	require('components/staff_change/directives/forms/exit_staff')
	require('components/staff_change/directives/forms/form_buttons')
	require('components/staff_change/directives/forms/job_change')
	require('components/staff_change/directives/forms/name_change')
	require('components/staff_change/directives/forms/new_staff')
	require('components/staff_change/directives/forms/start')
	require('components/staff_change/directives/forms/transfer_staff')
	require('components/staff_change/directives/tabs/exit_staff_list')
	require('components/staff_change/directives/tabs/job_change_list')
	require('components/staff_change/directives/tabs/name_change_list')
	require('components/staff_change/directives/tabs/new_staff_list')
	require('components/staff_change/directives/tabs/transfer_staff_list')
})
